name: Asana
on:
  issues:
    types: [opened]

jobs:
  create_task:
    name: Create Asana task
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: orbcorp/gha-create-asana-task
        with:
          asana-secret: ${{ secrets.ASANA_PAT }}
          asana-project-id: ${{ secrets.ASANA_PROJECT_ID }}
          asana-task-name: ${{ github.event.issue.title }}
          asana-task-description: ${{ github.event.issue.body }}
          asana-custom-fields: '{ "1205809189288915": "1205809189288916" }'
